# Generated by Django 5.1 on 2024-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('personal', 'personal'), ('business', 'business')], default='personal', max_length=200),
        ),
    ]
